# Generated by Django 5.1 on 2024-08-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suap', '0002_alter_aluno_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='suap/'),
        ),
    ]
